version: "3.9"

services:
  oracle-xe:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    platform: linux/amd64
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: MySecurePass123
    volumes:
      - ./data:/opt/oracle/oradata
    restart: unless-stopped